# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'victims.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from victim_search import Ui_victim_search
import sqlite3

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Victims(object):
#######################################################################################################################
    def indata(self):
	n1=self.vic_e_name.text()
	a1=self.vic_e_age.text()
	id1=self.vic_e_id.text()
	comboText1=self.vic_e_stat.currentText()
	comboText2=self.vic_e_sex_2.currentText()
	add1=self.vic_e_add1.text()
	adds1=self.vic_e_state.text()
	addc1=self.vic_e_count.text()
	iden1=self.vic_e_mark.text()
	comboText3=self.vic_e_cala.currentText()
	n = unicode(n1)
	a = unicode(a1)
	ids = unicode(id1)
	st = unicode(comboText1)
	se = unicode(comboText2)
	add = unicode(add1)
	adds = unicode(adds1)
	addc = unicode(addc1)
	iden = unicode(iden1)
	cala = unicode(comboText3)
	connection = sqlite3.connect("authenticate.db")
	connection.execute("INSERT INTO victim_entry VALUES(?,?,?,?,?,?,?,?,?,?)",[n,a,ids,st,se,add,adds,addc,iden,cala])
	print("Victim Details Added Successfully..!!")
	connection.commit()
	connection.close()
#######################################################################################################################
    def gosearch3(self):
	print("Vicitm Search Button clicked")
	self.victim_searchWindow=QtGui.QDialog() #object of new window
	self.ui= Ui_victim_search()		
	self.ui.setupUi(self.victim_searchWindow)
	self.victim_searchWindow.show()
#######################################################################################################################
    def setupUi(self, Victims):
        Victims.setObjectName(_fromUtf8("Victims"))
        Victims.resize(866, 610)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Victims.sizePolicy().hasHeightForWidth())
        Victims.setSizePolicy(sizePolicy)
        self.gridLayout_4 = QtGui.QGridLayout(Victims)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.status = QtGui.QLabel(Victims)
        self.status.setObjectName(_fromUtf8("status"))
        self.gridLayout.addWidget(self.status, 3, 0, 1, 1)
        self.name = QtGui.QLabel(Victims)
        self.name.setObjectName(_fromUtf8("name"))
        self.gridLayout.addWidget(self.name, 0, 0, 1, 1)
        self.vic_e_name = QtGui.QLineEdit(Victims)
        self.vic_e_name.setObjectName(_fromUtf8("vic_e_name"))
        self.gridLayout.addWidget(self.vic_e_name, 0, 2, 1, 1)
        self.vic_e_sex = QtGui.QLabel(Victims)
        self.vic_e_sex.setObjectName(_fromUtf8("vic_e_sex"))
        self.gridLayout.addWidget(self.vic_e_sex, 4, 0, 1, 1)
        self.vic_e_add1 = QtGui.QLineEdit(Victims)
        self.vic_e_add1.setObjectName(_fromUtf8("vic_e_add1"))
        self.gridLayout.addWidget(self.vic_e_add1, 7, 2, 1, 1)
        self.agerange = QtGui.QLabel(Victims)
        self.agerange.setObjectName(_fromUtf8("agerange"))
        self.gridLayout.addWidget(self.agerange, 1, 0, 1, 1)
        self.ID = QtGui.QLabel(Victims)
        self.ID.setObjectName(_fromUtf8("ID"))
        self.gridLayout.addWidget(self.ID, 2, 0, 1, 1)
        self.vic_e_age = QtGui.QLineEdit(Victims)
        self.vic_e_age.setObjectName(_fromUtf8("vic_e_age"))
        self.gridLayout.addWidget(self.vic_e_age, 1, 2, 1, 1)
        self.vic_e_id = QtGui.QLineEdit(Victims)
        self.vic_e_id.setObjectName(_fromUtf8("vic_e_id"))
        self.gridLayout.addWidget(self.vic_e_id, 2, 2, 1, 1)
        self.label = QtGui.QLabel(Victims)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 12, 0, 1, 1)
        self.vic_e_count = QtGui.QLineEdit(Victims)
        self.vic_e_count.setObjectName(_fromUtf8("vic_e_count"))
        self.gridLayout.addWidget(self.vic_e_count, 9, 2, 1, 1)
        self.identification = QtGui.QLabel(Victims)
        self.identification.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.identification.setObjectName(_fromUtf8("identification"))
        self.gridLayout.addWidget(self.identification, 11, 0, 1, 1)
        self.vic_e_mark = QtGui.QLineEdit(Victims)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vic_e_mark.sizePolicy().hasHeightForWidth())
        self.vic_e_mark.setSizePolicy(sizePolicy)
        self.vic_e_mark.setObjectName(_fromUtf8("vic_e_mark"))
        self.gridLayout.addWidget(self.vic_e_mark, 11, 2, 1, 1)
        self.address = QtGui.QLabel(Victims)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address.sizePolicy().hasHeightForWidth())
        self.address.setSizePolicy(sizePolicy)
        self.address.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.address.setObjectName(_fromUtf8("address"))
        self.gridLayout.addWidget(self.address, 7, 0, 1, 1)
        self.vic_e_state = QtGui.QLineEdit(Victims)
        self.vic_e_state.setObjectName(_fromUtf8("vic_e_state"))
        self.gridLayout.addWidget(self.vic_e_state, 8, 2, 1, 1)
        self.vic_e_sex_2 = QtGui.QComboBox(Victims)
        self.vic_e_sex_2.setObjectName(_fromUtf8("vic_e_sex_2"))
        self.vic_e_sex_2.addItem(_fromUtf8(""))
        self.vic_e_sex_2.addItem(_fromUtf8(""))
        self.vic_e_sex_2.addItem(_fromUtf8(""))
        self.vic_e_sex_2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.vic_e_sex_2, 4, 2, 1, 1)
        self.vic_e_cala = QtGui.QComboBox(Victims)
        self.vic_e_cala.setObjectName(_fromUtf8("vic_e_cala"))
        self.vic_e_cala.addItem(_fromUtf8(""))
        self.vic_e_cala.addItem(_fromUtf8(""))
        self.vic_e_cala.addItem(_fromUtf8(""))
        self.vic_e_cala.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.vic_e_cala, 12, 2, 1, 1)
        self.vic_e_stat = QtGui.QComboBox(Victims)
        self.vic_e_stat.setObjectName(_fromUtf8("vic_e_stat"))
        self.vic_e_stat.addItem(_fromUtf8(""))
        self.vic_e_stat.addItem(_fromUtf8(""))
        self.vic_e_stat.addItem(_fromUtf8(""))
        self.vic_e_stat.addItem(_fromUtf8(""))
        self.vic_e_stat.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.vic_e_stat, 3, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 0, 3, 2)
        self.vic_submit = QtGui.QPushButton(Victims)
        self.vic_submit.setObjectName(_fromUtf8("vic_submit"))
#######################################################################################################################
	self.vic_submit.clicked.connect(self.indata)
#######################################################################################################################
        self.gridLayout_4.addWidget(self.vic_submit, 4, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Victims)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 3, 2, 1, 1)
        self.vicentry = QtGui.QLabel(Victims)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vicentry.sizePolicy().hasHeightForWidth())
        self.vicentry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Symbola"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.vicentry.setFont(font)
        self.vicentry.setAlignment(QtCore.Qt.AlignCenter)
        self.vicentry.setObjectName(_fromUtf8("vicentry"))
        self.gridLayout_4.addWidget(self.vicentry, 0, 0, 1, 1)
        self.vic_search = QtGui.QPushButton(Victims)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vic_search.sizePolicy().hasHeightForWidth())
        self.vic_search.setSizePolicy(sizePolicy)
        self.vic_search.setObjectName(_fromUtf8("vic_search"))
#######################################################################################################################
	self.vic_search.clicked.connect(self.gosearch3)	
#######################################################################################################################
        self.gridLayout_4.addWidget(self.vic_search, 4, 1, 1, 1)

        self.retranslateUi(Victims)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Victims.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Victims.reject)
        QtCore.QMetaObject.connectSlotsByName(Victims)

    def retranslateUi(self, Victims):
        Victims.setWindowTitle(_translate("Victims", "Dialog", None))
        self.status.setText(_translate("Victims", "Status", None))
        self.name.setText(_translate("Victims", "Name", None))
        self.vic_e_name.setPlaceholderText(_translate("Victims", "First-Middle(if any)-Last", None))
        self.vic_e_sex.setText(_translate("Victims", "Sex", None))
        self.vic_e_add1.setPlaceholderText(_translate("Victims", "Main Line", None))
        self.agerange.setText(_translate("Victims", "Age Range", None))
        self.ID.setText(_translate("Victims", "ID ", None))
        self.label.setText(_translate("Victims", "Calamity", None))
        self.vic_e_count.setPlaceholderText(_translate("Victims", "Country", None))
        self.identification.setText(_translate("Victims", "Any Identification", None))
        self.address.setText(_translate("Victims", "Address", None))
        self.vic_e_state.setPlaceholderText(_translate("Victims", "State", None))
        self.vic_e_sex_2.setItemText(0, _translate("Victims", "Select one from below", None))
        self.vic_e_sex_2.setItemText(1, _translate("Victims", "Male", None))
        self.vic_e_sex_2.setItemText(2, _translate("Victims", "Female", None))
        self.vic_e_sex_2.setItemText(3, _translate("Victims", "Transgender", None))
        self.vic_e_cala.setItemText(0, _translate("Victims", "Select one from below", None))
        self.vic_e_cala.setItemText(1, _translate("Victims", "Flood", None))
        self.vic_e_cala.setItemText(2, _translate("Victims", "Earthquake", None))
        self.vic_e_cala.setItemText(3, _translate("Victims", "Drought", None))
        self.vic_e_stat.setItemText(0, _translate("Victims", "Select one from below", None))
        self.vic_e_stat.setItemText(1, _translate("Victims", "Released", None))
        self.vic_e_stat.setItemText(2, _translate("Victims", "Hospitalized", None))
        self.vic_e_stat.setItemText(3, _translate("Victims", "Expired", None))
        self.vic_e_stat.setItemText(4, _translate("Victims", "Not Found", None))
        self.vic_submit.setText(_translate("Victims", "Submit Victim Details", None))
        self.vicentry.setText(_translate("Victims", "Victims Entry", None))
        self.vic_search.setText(_translate("Victims", "Click here to Search Victims", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Victims = QtGui.QDialog()
    ui = Ui_Victims()
    ui.setupUi(Victims)
    Victims.show()
    sys.exit(app.exec_())

